# Site settings
title: Ayuda de Isolaatti
email: software@isolaatti.com
description: >
  Ayuda de Isolaatti
lang: es-MX

baseurl: "/" # the subpath of your site, e.g. /blog/
url: https://isolaatti-software.github.io/ # the base hostname & protocol for your site
git_address: https://github.com/Isolaatti-Software/Isolaatti-Software.github.io
git_edit_address: https://github.com/Isolaatti-Software/Isolaatti-Software.github.io/blob/main

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: paper # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
